Next10 + change in some images
bstnfrmry/hanabi pull request #201
Opened 2020-11-04 12:56 UTC by sarahmamy

Let me know if you prefer me finishing or if you'd rather merge step by step

2020-11-04 13:01 UTC, bstnfrmry approved these changes

2020-11-06 19:08 UTC, bstnfrmry requested changes
@sarahmamy let's merge this and do the i18n part in a second time 👍

2020-11-06 19:08 UTC, bstnfrmry commented on package.json
> +    "next": "10",
Use "^10" to say "10 or any minor version above that (10.1, 10.2, ...), so we're not locked with 10

2020-11-22 12:12 UTC, sarahmamy commented
Added i18n modification

2020-11-22 21:49 UTC, benjamintd approved these changes

2020-11-22 22:41 UTC, merged