Fix Bug when card could not be revealed
bstnfrmry/hanabi pull request #205
Opened 2020-11-28 16:55 UTC by sarahmamy

2020-11-29 15:43 UTC, bstnfrmry requested changes

2020-11-29 15:43 UTC, bstnfrmry commented on src/components/game.tsx
> +    document.addEventListener("keydown", checkKey);
We usually bind global events to `window` rather than `document`. Just conventions stuff. This avoid you having to do this weird `e = e || window.event;` above.

Also, it's usually best to use `keyup`. Not 100% sure in this case you should try and see the difference. The difference would basically be when you keep the key pressed.

2020-11-29 15:43 UTC, bstnfrmry commented on src/components/game.tsx
> +    function checkKey(e) {
`e` is of type `KeyboardEvent`. Also, 1 letter variables names are usually not recommended for readability 😉

2020-11-29 15:43 UTC, bstnfrmry commented on src/components/game.tsx
> +      if (e.keyCode == "37" && cursor === null) {
`e.keyCode` is a number. You're comparing it with a string. It happens to work because your usually shallow equal (`==`) which is generally not recommended.

2020-11-29 15:43 UTC, bstnfrmry commented on src/components/replayViewer.tsx
> +      <Button void className="ml3 pointer:hover" size={ButtonSize.TINY} text="&times;" onClick={onStopReplay} />
Pretty sure this is not the right class name. Have you tried it?

2020-12-03 16:26 UTC, sarahmamy commented on src/components/replayViewer.tsx
> +      <Button void className="ml3 pointer:hover" size={ButtonSize.TINY} text="&times;" onClick={onStopReplay} />
![image](https://user-images.githubusercontent.com/16375291/101057708-a4b5bf00-358c-11eb-8831-b4ed23d0e506.png)
found it in their doc and double-checked it

2020-12-03 16:30 UTC, merged